#!/bin/bash

echo "📋 SETUP CHECKLIST"
echo "=================="
echo ""
echo "Before running the app, complete these steps:"
echo ""
echo "1. ✅ Dependencies installed (npm install already done)"
echo ""
echo "2. 📝 Edit .env.local with your credentials:"
echo "   - Open: .env.local"
echo "   - Add your Supabase URL, keys"
echo "   - Add your Stripe test keys"
echo ""
echo "3. 🗄️ Set up Supabase database:"
echo "   - Go to: https://supabase.com/dashboard"
echo "   - Open your project: protest-signs-website"
echo "   - Go to: SQL Editor (left sidebar)"
echo "   - Click: New query"
echo "   - Copy contents from: supabase/schema.sql"
echo "   - Paste and Run (Ctrl/Cmd + Enter)"
echo "   - Wait for success message"
echo ""
echo "4. 📦 Create Storage Bucket:"
echo "   - In Supabase dashboard: Storage → New bucket"
echo "   - Name: sign-images"
echo "   - Public: ✓ YES (check this)"
echo "   - Create"
echo ""
echo "5. 🚀 Run the dev server:"
echo "   npm run dev"
echo ""
echo "6. 👤 Create admin account:"
echo "   - Go to: http://localhost:3000/auth/signup"
echo "   - Sign up with your email"
echo "   - Confirm email (check inbox)"
echo "   - In Supabase: Table Editor → profiles"
echo "   - Find your user, set is_admin = true"
echo ""
echo "📖 For detailed instructions, see: SETUP.md"
